### ISSUE TITLE
can't download LFWA+dataset

### ISSUE THREAD

**Issue by gucasbrg** [wondonghyeon/face-classification#1]
I can't LFWA+dataset in dropbox,the address is error ;
Can I get these files in the other path? tks

**Comment by wondonghyeon** [comment]
Please contact the authors of the following paper.
https://arxiv.org/pdf/1411.7766.pdf

**Comment by chenzeyuczy** [comment]
Can anyone share a copy for the LFWA+ dataset? Since it is still a bti troublesome to contanct the authors.

**Comment by xudou3** [comment]
I meet the same problem. Can anyone share new link for download LFWA+ dataset?

**Comment by JoshuaQYH** [comment]
I met this problem too... The link is invalid...Anybody can share a new link for LFWA+ dataset...

**Comment by benitofe** [comment]
Hi everybody, I sent a email to Xiaoou Tang (xtang@@ie.cuhk.edu.hk) asking for sharing the dataset with me, and he did it.

**Comment by JoshuaQYH** [comment]
> Hi everybody, I sent a email to Xiaoou Tang (xtang@@ie.cuhk.edu.hk) asking for sharing the dataset with me, and he did it.

Wow, Can you share the dataset link for us?

**Comment by benitofe** [comment]
Try this link:
https://drive.google.com/drive/u/0/folders/0B7EVK8r0v71pQ3NzdzRhVUhSams

**Comment by JoshuaQYH** [comment]
> Try this link:
> https://drive.google.com/drive/u/0/folders/0B7EVK8r0v71pQ3NzdzRhVUhSams

Wow! Thank you so much !

**Comment by mutexlocker** [comment]
I find gender labels wrong in the mat file. Can you confirm it? 
For example Zoran_Djindjic has 4 pictures and 3 of them are labeled man and 1 female.
are the file names in the 'name' associated with the labels in 'label'  in order?
first row in 'name' is associated with first row in the 'labels' ?
