### ISSUE TITLE
lmao what is this? joke?

### ISSUE THREAD

**Issue by togersonS** [wondonghyeon/face-classification#15]
wtf is this?

print "WARNING: The array", name, "requires > 2Gb"

  Cell In[1], line 7
    from mat73_to_pickle import *

  File ~/face-classification/mat73_to_pickle.py:65
    print "WARNING: The array", name, "requires > 2Gb"
    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by wondonghyeon** [comment]
Hi, this was my grad school project and I was using Python 2 back then. I don't plan to maintain this repo. Thanks for understanding.
